module.exports = {
    testBalance: {'USD' : 50, 'XRP' : 0},
    longPosition: false,
    spread: 1,
    bid: -1,
    ask: -1,
    buyPrice: 1,
    min: Infinity,
    pair: 'XRPUSD',
    first: 'XRP',
    second: 'USD',
    completePair: 'XXRPZUSD',
    searcher: 'data.result.XXRPZUSD',
    tradeHistory: [],
    last: 10000,
    data: [],
    array: [],
    index: 0,
    parameter: 0,
    localHistory: []
}
